Repository zap-lab/zap, pull requests merged in 2020-07, with the labels that each got.

#25 feature/unify-conventions
  .editorconfig
  .eslintrc.js
  .prettierrc.js
  .storybook/main.js
  package.json
  src/components/Container.tsx
  src/components/Header.tsx
  src/components/LayoutMain.tsx
  src/components/LayoutRoot.tsx
  src/components/Page.tsx
  src/components/articles/Article.tsx
  src/components/articles/ArticleContent.tsx
  src/components/articles/Description.tsx
  src/components/articles/Title.tsx
  src/layouts/index.tsx
  src/pages/404.tsx
  src/pages/index.tsx
  src/pages/page-2.tsx
  src/styles/getEmSize.ts
  src/styles/mixins.ts
  src/styles/normalize.ts
  src/styles/variables.ts
  src/templates/page.tsx
  src/typings.d.ts
  tsconfig.json
  yarn.lock
Labels: flow: to be review

#13 feature/add-github-template
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: flow: to be review

#31 fix/base-url
  .gitignore
  gatsby-config.js
  package.json
  public/index.html
  public/page-data/404.html/page-data.json
  public/page-data/404/page-data.json
  public/page-data/a-markdown-page/page-data.json
  public/page-data/dev-404-page/page-data.json
  public/page-data/index/page-data.json
  public/page-data/page-2/page-data.json
  public/static/d/991718019.json
  yarn.lock
Labels: flow: to be review, issue: bug

#30 feature/add-jest
  .babelrc.js
  .gitignore
  .vscode/settings.json
  package.json
  public/index.html
  public/page-data/404.html/page-data.json
  public/page-data/404/page-data.json
  public/page-data/a-markdown-page/page-data.json
  public/page-data/dev-404-page/page-data.json
  public/page-data/index/page-data.json
  public/page-data/page-2/page-data.json
  src/components/LayoutMain.test.tsx
  tsconfig.json
  yarn.lock
Labels: flow: to be merged, type: proposal

#32 feat: add ci yml
  .babelrc.js
  .github/workflows/ci.yml
  package.json
  public/index.html
  public/page-data/404.html/page-data.json
  public/page-data/404/page-data.json
  public/page-data/a-markdown-page/page-data.json
  public/page-data/dev-404-page/page-data.json
  public/page-data/index/page-data.json
  public/page-data/page-2/page-data.json
  yarn.lock
Labels: flow: to be merged
